### ISSUE TITLE
Feature/Optimization: Ability to merge multiple separate lines vertex arrays into the same mesh

### ISSUE THREAD

**Issue by patricknelson** [johannesugb/VolumetricLinesUnity#4]
Would it be possible to update the API so that it could accept another property/parameter where you could define an array of indices/offsets where gaps should occur in the line vertices? That way you still have a single efficient mesh loaded into the GPU if you're looking to render a large number of separate lines at once.

**Explanation:** I'm interested in utilizing this asset for a rendering a live data visualization that renders batches of 30 - 150 curves every second (each containing many line segments) and with each batch removed over time (e.g. 30s). Think of arcs being drawn on a globe (e.g. from Paris to London). I've built previous versions of this in WegGL using THREE.js and had success optimizing it such that a single batch of 150 curves (and thus many line segments) are drawn at once, just doubling up vertices and leaving a large gap between each new arc. In my previous version, it was a simple vert/frag shader in GLSL using [`THREE.LineSegments`](https://threejs.org/docs/#api/objects/LineSegments) which uses gl.LINES for this optimization, so now I'm looking to retain this optimization in Unity via meshes since using GL Lines in Unity appears to be CPU-bound.

I'm new to Unity/C# but would be interested in possibly submitting a PR for this if I can manage to figure it out :)

**Comment by patricknelson** [comment]
Looking back at this, I almost thought that  `VolumetricMultiLineBehavior` would be my solution for this (and wouldn't require rendering a strip mesh which I'm fine with), however, I'm uncertain if this would be efficient since it has to create a new `GameObject` and also instantiates a separate line segment and an associated `VolumetricLineBehavior` for each object. So, maybe the overall solution would be:

- Consolidate API's such that you have a new `bool m_isMultiLine` property
- Update functionality so that multi-line means that you must have an even number of vertices and lines are only drawn between odd -> even vertices (even -> odd has a gap).

This means the upgrade path could be:

- `VolumetricLineStripBehavior` gets new property `bool m_isMultiLine` as defined above.
- `VolumetricLineBehavior` changes to accept multiple points (works like `VolumetricLineStripBehavior`, just without using a strip mesh)
- Add new property to `VolumetricLineBehavior` as well to accept multiline behavior (`bool m_isMultiLine`) which then changes how it draws lines. This way `VolumetricMultiLineBehavior.cs` becomes redundant (and would be less efficient anyway).

Thoughts? I could be way off here, so just throwing it out there! (again I'm new)

**Comment by johannesugb** [comment]
Thank you for your thoughts and the proposal. 

So, if I understood it correctly, what you want to achieve is basically a multi-line where several line segments are left out. Is that correct?

I am not in favour of adding that functionality to the asset, because it is rather specific to a certain use case.  In fact, I was thinking about removing `VolumetricMultiLineBehavior` from the asset because from a technical point of view, it is just a usage scenario of `VolumetricLineBehavior`. The basic building blocks of the asset are the `VolumetricLineBehavior` and the `VolumetricLineStripBehavior`. For this reason, I would not add a `m_isMultiLine` to the latter.

The asset shall provide the basic building blocks and some examples. So, I think, I'll degrade `VolumetricMultiLineBehavior` to an example in the next release.

One thing, that might interest you: I am working on a new asset which is capable of rendering huge numbers of volumetric lines efficiently by making use of instancing, among other optimizations, minimizing the draw calls and maximizing performance. Not sure, however, when I'll be able to release it.

**Comment by patricknelson** [comment]
> So, if I understood it correctly, what you want to achieve is basically a multi-line where several line segments are left out. Is that correct?

Yes, basically. Just as an optimization so you can batch multiple distinct groups of segments together into the same mesh (if that’s even possible). By the way, this could apply to the strip or to the line (and I think I agree on `VolumetricMultiLineBehavior`).

Maybe one way of accomplishing the break in the line segments could be to pass an array of vertex indices where each break should occur. E.g. Say you wanted to have two straight lines drawn at once (overly simplistic example), you would have 3 segments composed of 4 vertices and you could call `lineSegments.setBreaks(new int[] { 1 });`
